### ISSUE TITLE
s-bind-video s-bind-audio snippets

### ISSUE THREAD

**Issue by subz390** [fivethree-team/vscode-svelte-snippets#8]
I just notice the `s-bind-video` snippet is missing quite a lot of parameters, and there's no `s-bind-audio` snippet
https://svelte.dev/docs#Media_element_bindings

```html
<video
  src={clip}
  bind:duration
  bind:buffered
  bind:played
  bind:seekable
  bind:seeking
  bind:ended
  bind:currentTime
  bind:playbackRate
  bind:paused
  bind:volume
  bind:muted
  bind:videoWidth
  bind:videoHeight
></video>
```

```html
<audio
  src={clip}
  bind:duration
  bind:buffered
  bind:played
  bind:seekable
  bind:seeking
  bind:ended
  bind:currentTime
  bind:playbackRate
  bind:paused
  bind:volume
  bind:muted
></audio>
```

**Comment by marcjulian** [comment]
@subz390 Thanks for reporting. Do you mind creating a PR for the parameters?

**Comment by subz390** [comment]
@marcjulian sure gimme a day or so, I'll schedule it in when I have a moment.

**Comment by marcjulian** [comment]
@subz390 of course 👍  thank you

**Comment by subz390** [comment]
@marcjulian on wrapping up, I just want to say thanks for the smooth and efficient turn-a-round.

**Comment by marcjulian** [comment]
@subz390 no problem. PRs are always welcome!
